### ISSUE TITLE
Http authentification question

### ISSUE THREAD

**Issue by Lacoz** [toyama0919/embulk-input-elasticsearch#7]
I like to try your input plugin, it is possible to extend configuration of host to allow http authentification (search guard), on self signed ssl host? My es is acessible with $curl -k https://testuser:testpass@localhost:9200 . Thanks

**Comment by kakoni** [comment]
Late to the party put you can do this;
```
in:
  type: elasticsearch
  nodes:
    - {host: localhost, port: 9200, scheme: https, user: 'testuser', password: 'testpass'}
```
